name: home_indicator
description: Flutter plugin to show/hide the home indicator on iPhones without home button.
version: 2.0.2
homepage: https://github.com/RainwayApp/flutter_home_indicator

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      # android:
      #   package: com.example.home_indicator
      #   pluginClass: HomeIndicatorPlugin
      ios:
        pluginClass: HomeIndicatorPlugin
